### ISSUE TITLE
wpa_supplicant starts on all wireless interfaces

### ISSUE THREAD

**Issue by nswint** [martinsauter/WLAN-VPN-Pi#12]
wpa_supplicant enumerates all wireless interfaces, including wlan0,wlan2. Previously it was only on wlan1.

Please prevent wpa_supplicant from using wlan0 and wlan(x+1).

**Comment by martinsauter** [comment]
Yes I noticed, that, too. Unfortunately I have no idea so far how to fix this.

**Comment by martinsauter** [comment]
O.k. good and bad news here:

1. Good news: Here's how to fix the enumeration. Rename /etc/wpa_supplicant.conf into /etc/wpa_supplicant-wlan1.conf. Important: The first word separator is an underscore as before, the second one before wlan1 is a minus! Make sure wpa_supplicant.conf is no longer present! This way dhcpcd only uses the Wifi client configuration for wlan1. 

2. Bad news: With both Wifis active, one acting as AP the other as client, AP functionality continues being unstable. When downloading large files it only takes a few minutes before wlan0 (the AP) stops working. I am not sure what the issue here is. I made sure different Wifi channels are used and I separated the Wifi dongle from the Pi with a 1.5m USB cable but the result is still the same. Also, there's no clue in syslog why hostapd has stopped working.
